language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
gemfile:
  - gemfiles/Gemfile.rails-3.2.ci
  - gemfiles/Gemfile.rails-4.0.ci
  - gemfiles/Gemfile.rails-4.1.ci
  - gemfiles/Gemfile.rails-4.2.ci
script:
  - bundle exec rspec
  - bundle exec rubocop
